project:
  type: website
  resources: 
    - "_headers"
website:
  title: "Eleanor Jackson"
  favicon: images/icon.png
  site-url: https://eleanorjackson.com
  description: Research scientist and ecologist 
  repo-url: https://github.com/ee-jackson/quarto-site
  search: false
  image: "https://eleanorjackson.com/images/icon.png"
  open-graph:
    locale: en_GB
    image: images/icon.png
  navbar:
    title: false
    logo: images/logo.png
    left:
      - href: publications.qmd
        text: Publications
  page-footer:
    left: |
      {{< fa regular copyright >}} Eleanor Jackson, 2025
      
    right: |
      <a href="https://github.com/ee-jackson/quarto-site" title="source code">{{< fa regular code >}}</a>
format:
  html:
    theme: custom.css
    css: styles.css
    toc: true
lang: en-GB
editor: source
pagetitle: "{{< meta title >}}"