project:
  type: website
website:
  title: "eleanor jackson"
  favicon: images/icon.png
  site-url: https://eleanor-jackson.com
  description: Research scientist with interests in community ecology, forest ecology and plant-insect interactions.
  repo-url: https://github.com/ee-jackson/quarto-site
  search: false
  twitter-card:
    creator: "@ee_jackson"
    card-style: summary
  navbar:
    title: false
    logo: images/logo.png
    left:
      - href: research.qmd
        text: research
      - href: publications.qmd
        text: pubs
      - href: post.qmd
        text: blog
  page-footer:
    left: |
      {{< fa regular copyright >}} Eleanor Jackson, 2024
      
    right: |
      <a href="https://github.com/ee-jackson/quarto-site" title="source code">{{< fa regular code >}}</a>
format:
  html:
    theme: custom.css
    css: styles.css
    toc: true
lang: en-GB
editor: source
pagetitle: "{{< meta title >}}"