project:
  type: website
  post-render:
    - "cp -rnv static/. _site/"

website:
  title: "eleanor jackson"
  favicon: images/icon.png
  site-url: https://www.eleanor-jackson.com
  description: Research scientist with interests in community ecology, forest ecology and plant-insect interactions.
  repo-url: https://github.com/ee-jackson/quarto-site
  search: false
  twitter-card:
    creator: "@ee_jackson"
    card-style: summary
  navbar:
    title: false
    logo: images/logo.png
    left:
      - href: about.qmd
        text: about
      - href: research.qmd
        text: research
      - href: publications.qmd
        text: pubs
      - href: post.qmd
        text: blog
  page-footer:
    left: |
      {{< fa regular copyright >}} Eleanor Jackson, 2023
      
    right: |
      [{{< fa regular code >}}](https://github.com/ee-jackson/quarto-site)
format:
  html:
    theme: custom.css
    css: styles.css
    toc: true
lang: en-GB
editor: source
