---
pagetitle: "about"
format:
  html:
    toc: false
---
# currently

I am a PhD student and Research Associate at the University of Reading. I combine field work with quantitative methods to answer questions like: "why are there so many tree species in tropical forests?" and "can we predict the effect of restoration actions on individual ecosystems?". You can read about my current research [here](/research.qmd).

I think we should be working towards reproducibility and openness in science. I serve on the media committee for the [Society for Open, Reliable, and Transparent Ecology and Evolutionary biology (SORTEE)](https://www.sortee.org) and am an [Open Research Champion](https://research.reading.ac.uk/open-research-champions/) at my university.

# previously

I was a Publishing Assistant at Springer Nature and prior to that I was a Research Associate at the University of Hamburg. I completed a BSc in Zoology at the University of Exeter and became a Master of Research (MRes) in Biodiversity, Evolution & Conservation at University College London.

My previous research has seen me experimentally evolving phytoplankton in mesocosms, culturing bacteria from amphibian microbiomes and sequencing DNA from meltwater ponds in Antarctica.
